// What happens when you run the following program? Why do we get that result?
{
  let foo = "bar";
}

console.log(foo);

// The foo variable is declared inside of a block. It will return an error.
